# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../FATS\Codes\mofidBroker\easytraderdialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(710, 483)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 10, 170, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.openChromeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.openChromeButton.setObjectName("openChromeButton")
        self.verticalLayout_2.addWidget(self.openChromeButton)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.openEasyTraderInChromeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.openEasyTraderInChromeButton.setObjectName("openEasyTraderInChromeButton")
        self.verticalLayout.addWidget(self.openEasyTraderInChromeButton)
        self.loginEasyTraderButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loginEasyTraderButton.setObjectName("loginEasyTraderButton")
        self.verticalLayout.addWidget(self.loginEasyTraderButton)
        self.loadEasyTraderButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadEasyTraderButton.setObjectName("loadEasyTraderButton")
        self.verticalLayout.addWidget(self.loadEasyTraderButton)
        self.loadCookieFromDBButton = QtWidgets.QPushButton(self.layoutWidget)
        self.loadCookieFromDBButton.setObjectName("loadCookieFromDBButton")
        self.verticalLayout.addWidget(self.loadCookieFromDBButton)
        self.testResponceButton = QtWidgets.QPushButton(self.layoutWidget)
        self.testResponceButton.setObjectName("testResponceButton")
        self.verticalLayout.addWidget(self.testResponceButton)
        self.closeChromeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.closeChromeButton.setObjectName("closeChromeButton")
        self.verticalLayout.addWidget(self.closeChromeButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(270, 10, 161, 199))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.openSearchMenuButton = QtWidgets.QPushButton(self.widget)
        self.openSearchMenuButton.setObjectName("openSearchMenuButton")
        self.verticalLayout_3.addWidget(self.openSearchMenuButton)
        self.closeSearchMenuButton = QtWidgets.QPushButton(self.widget)
        self.closeSearchMenuButton.setObjectName("closeSearchMenuButton")
        self.verticalLayout_3.addWidget(self.closeSearchMenuButton)
        self.focusOnSymbolButton = QtWidgets.QPushButton(self.widget)
        self.focusOnSymbolButton.setObjectName("focusOnSymbolButton")
        self.verticalLayout_3.addWidget(self.focusOnSymbolButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_3.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(60, 230, 161, 199))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_5.addWidget(self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_5.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_5.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_5.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_5.addWidget(self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_5.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_5.addWidget(self.pushButton_21)
        self.layoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_3.setGeometry(QtCore.QRect(270, 230, 161, 199))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_6.addWidget(self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_6.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_6.addWidget(self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_6.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_6.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_6.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_6.addWidget(self.pushButton_28)
        self.layoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_4.setGeometry(QtCore.QRect(480, 230, 161, 199))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_36 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_36.setObjectName("pushButton_36")
        self.verticalLayout_8.addWidget(self.pushButton_36)
        self.pushButton_37 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_37.setObjectName("pushButton_37")
        self.verticalLayout_8.addWidget(self.pushButton_37)
        self.pushButton_38 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_38.setObjectName("pushButton_38")
        self.verticalLayout_8.addWidget(self.pushButton_38)
        self.pushButton_39 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_39.setObjectName("pushButton_39")
        self.verticalLayout_8.addWidget(self.pushButton_39)
        self.pushButton_40 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_40.setObjectName("pushButton_40")
        self.verticalLayout_8.addWidget(self.pushButton_40)
        self.pushButton_41 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_41.setObjectName("pushButton_41")
        self.verticalLayout_8.addWidget(self.pushButton_41)
        self.pushButton_42 = QtWidgets.QPushButton(self.layoutWidget_4)
        self.pushButton_42.setObjectName("pushButton_42")
        self.verticalLayout_8.addWidget(self.pushButton_42)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(480, 10, 162, 201))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_4.addWidget(self.pushButton_14)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.layoutWidget.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_11.raise_()
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.openChromeButton.setText(_translate("Dialog", "openChrome"))
        self.openEasyTraderInChromeButton.setText(_translate("Dialog", "openEasyTraderInChrome"))
        self.loginEasyTraderButton.setText(_translate("Dialog", "autoLoginEasyTrader"))
        self.loadEasyTraderButton.setText(_translate("Dialog", "loadEasyTrader"))
        self.loadCookieFromDBButton.setText(_translate("Dialog", "getRemainMoneyByCode"))
        self.testResponceButton.setText(_translate("Dialog", "testResponce"))
        self.closeChromeButton.setText(_translate("Dialog", "closeChrome"))
        self.openSearchMenuButton.setText(_translate("Dialog", "openSearchMenu"))
        self.closeSearchMenuButton.setText(_translate("Dialog", "closeSearchMenu"))
        self.focusOnSymbolButton.setText(_translate("Dialog", "focusOnSymbol"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_15.setText(_translate("Dialog", "15"))
        self.pushButton_16.setText(_translate("Dialog", "16"))
        self.pushButton_17.setText(_translate("Dialog", "17"))
        self.pushButton_18.setText(_translate("Dialog", "18"))
        self.pushButton_19.setText(_translate("Dialog", "19"))
        self.pushButton_20.setText(_translate("Dialog", "20"))
        self.pushButton_21.setText(_translate("Dialog", "21"))
        self.pushButton_22.setText(_translate("Dialog", "22"))
        self.pushButton_23.setText(_translate("Dialog", "23"))
        self.pushButton_24.setText(_translate("Dialog", "24"))
        self.pushButton_25.setText(_translate("Dialog", "25"))
        self.pushButton_26.setText(_translate("Dialog", "26"))
        self.pushButton_27.setText(_translate("Dialog", "27"))
        self.pushButton_28.setText(_translate("Dialog", "28"))
        self.pushButton_36.setText(_translate("Dialog", "36"))
        self.pushButton_37.setText(_translate("Dialog", "37"))
        self.pushButton_38.setText(_translate("Dialog", "38"))
        self.pushButton_39.setText(_translate("Dialog", "39"))
        self.pushButton_40.setText(_translate("Dialog", "40"))
        self.pushButton_41.setText(_translate("Dialog", "41"))
        self.pushButton_42.setText(_translate("Dialog", "42"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_10.setText(_translate("Dialog", "10"))
        self.pushButton_11.setText(_translate("Dialog", "11"))
        self.pushButton_12.setText(_translate("Dialog", "12"))
        self.pushButton_13.setText(_translate("Dialog", "13"))
        self.pushButton_14.setText(_translate("Dialog", "14"))
